### ISSUE TITLE
while testing example in the tutorial

### ISSUE THREAD

**Issue by rroderich** [ufal/neuralmonkey#155]
2016-11-24 21:04:26: Failed to load INI file: Error while loading 'decoder': module 'magic' has no attribute 'magic_load'
Traceback:   File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 140, in load_config_file
    value, config_dicts, existing_objects, 0)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in build_object
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in <listcomp>
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in build_object
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in <listcomp>
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 107, in instantiate_class
    obj = clazz(*bounded_params.args, **bounded_params.kwargs)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 62, in load_dataset_from_files
    for key, path in series_paths.items()}
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 62, in <dictcomp>
    for key, path in series_paths.items()}
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 131, in create_dataset_series
    magic.magic_load(filetyper.cookie, None)

Traceback (most recent call last):
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 44, in load_file
    config_dict = load_config_file(config_f, self.ignored)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 142, in load_config_file
    raise ConfigBuildException(key, exc) from None
neuralmonkey.config.exceptions.ConfigBuildException: Error while loading 'decoder': module 'magic' has no attribute 'magic_load'
Traceback:   File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 140, in load_config_file
    value, config_dicts, existing_objects, 0)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in build_object
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in <listcomp>
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 90, in instantiate_class
    depth + 1)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in build_object
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 44, in <listcomp>
    for val in value]
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 57, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 107, in instantiate_class
    obj = clazz(*bounded_params.args, **bounded_params.kwargs)
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 62, in load_dataset_from_files
    for key, path in series_paths.items()}
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 62, in <dictcomp>
    for key, path in series_paths.items()}
  File "/home/marcel/neuralmonkey/bin/neuralmonkey/dataset.py", line 131, in create_dataset_series
    magic.magic_load(filetyper.cookie, None)

**Comment by jlibovicky** [comment]
It seems like you are using a different version of [python-magic](https://pypi.python.org/pypi/python-magic) than we do. I works for me with version 0.4.12 with Python 3.5.

**Comment by jindrahelcl** [comment]
see the requiremetns.txt file in the root dir of this repository - there is a tested version of the package

**Comment by obo** [comment]
closing, feel free to reopen if the issue remains in master after decoder_refactor is merged in
