### ISSUE TITLE
Postprocessing bug

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#20]
When I ran my `tests/small.ini` configuration, it failed on some error with lambda wanting two arguments, but just one was given. I solved this in my branch by removing the second (unused) argument of the lambda on line 36 in learning_utils, but I'm not sure whether this does not break anything else. Can you have a look at this, @jindrahelcl?

Edit: The correct lambda was on line 155, but maybe they should be the same?

**Comment by tomasmcz** [comment]
Here is the traceback:
```
Traceback (most recent call last):

  File "/opt/python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main

    "__main__", fname, loader, pkg_name)

  File "/opt/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code

    exec code in run_globals

  File "/home/travis/build/ufal/neuralmonkey/neuralmonkey/train.py", line 149, in <module>

    main()

  File "/home/travis/build/ufal/neuralmonkey/neuralmonkey/train.py", line 142, in main

    minimize_metric=args.minimize)

  File "neuralmonkey/learning_utils.py", line 194, in training_loop

    val_tgt_sentences = postprocess(val_raw_tgt_sentences)

TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by jindrahelcl** [comment]
Yeah, that's OK. I was removing the second argument which was the whole dataset and which was unused everywhere else, but I did not try that without a postprocessor.
