### ISSUE TITLE
Validation dataset failing on _print_examples 

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#313]
There should be a check, that the validation set is not lazy, otherwise it will fail:

Traceback (most recent call last):
  File "neuralmonkey/bin/neuralmonkey-train", line 6, in <module>
    main()
  File "neuralmonkey/bin/neuralmonkey/train.py", line 186, in main
    minimize_metric=cfg.model.minimize)
  File "neuralmonkey/bin/neuralmonkey/learning_utils.py", line 251, in training_loop
    val_preview_num_examples)
  File "neuralmonkey/bin/neuralmonkey/learning_utils.py", line 527, in _print_examples
    for i in range(min(len(dataset), num_examples)):
  File "neuralmonkey/bin/neuralmonkey/dataset.py", line 207, in __len__
    raise Exception("Lazy dataset does not know its size")
Exception: Lazy dataset does not know its size

**Comment by jindrahelcl** [comment]
stačí když se na řádce 527 vylepší ta podmínka. zbytek by měl bejt vyřešenej vyřešením terroru (#307)
