### ISSUE TITLE
 "Cannot import module {}.".format(module_name))

### ISSUE THREAD

**Issue by supriyalk** [ufal/neuralmonkey#503]
After installing and while going through the tutorial, when I run the command bin/neuralmonkey-train exp-nm-ape/post-edit.ini I get the following error: 

2017-07-25 09:47:33: Loading INI file: 'exp-nm-ape/post-edit.ini'
2017-07-25 09:47:33: INI file is parsed.
2017-07-25 09:47:33: Building model based on the config.
2017-07-25 09:47:33: Failed to build model: Error while loading 'runners': Cannot import module neuralmonkey.encoders  .sentence_encoder.
Traceback:   File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 198, in build_con  fig
    value, config_dicts, existing_objects, 0)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in build_object
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in <listcomp>
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 148, in instantiate_class
    depth + 1)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 148, in instantiate_class
    depth + 1)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in build_object
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in <listcomp>
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 134, in instantiate_class
    clazz = this_dict['class'].create()
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 47, in create
    "Cannot import module {}.".format(module_name))

Traceback (most recent call last):
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 86, in build_model
    model = build_config(self.config_dict, self.ignored, warn_unused)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 200, in build_config
    raise ConfigBuildException(key, exc) from None
neuralmonkey.config.exceptions.ConfigBuildException: Error while loading 'runners': Cannot import module neuralmonkey  .encoders.sentence_encoder.
Traceback:   File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 198, in build_con  fig
    value, config_dicts, existing_objects, 0)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in build_object
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in <listcomp>
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 148, in instantiate_class
    depth + 1)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 148, in instantiate_class
    depth + 1)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in build_object
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 96, in <listcomp>
    for val in value]
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 134, in instantiate_class
    clazz = this_dict['class'].create()
  File "/home/slkapur/rnn_studies/neuralmonkey/bin/neuralmonkey/config/builder.py", line 47, in create
    "Cannot import module {}.".format(module_name))

I have verified that I am running python 3.5.2 and am on a linux system. Does anyone have any idea what the issue may be?

**Comment by jindrahelcl** [comment]
Yes, sorry, there was a typo in tutorial documentation. In the configuration file, replace sentence_encoder with recurrent. Like this:

```
class=encoders.recurrent.SentenceEncoder
```

the rest should work.

The documentation is fixed, but it has not been built yet due to an error in readthedocs. I will look into it.

Thanks

**Comment by supriyalk** [comment]
in the configuration.py file? What line is it on, I am not able to find where to replace

**Comment by jindrahelcl** [comment]
No, not in `configuration.py`. When you run the command

```
neuralmonkey-train something.ini
```

it is the `something.ini` file.

Sorry for confusion.

**Comment by supriyalk** [comment]
after changing sentence_encoder to recurrent in two places, I am now getting the error: Failed to build model: Error while loading 'runners': Error while loading '<class 'neuralmonkey.decoders.decoder.Decoder'>': got an unexpected keyword argument 'embeddings_encoder'

Does the decoder need to be changed to recurrent as well?

**Comment by jindrahelcl** [comment]
Oh, I see. I am afraid there are going to be multiple changes to the tutorial.

If you want to get started, just change the configuration file back to sentence_encoder and use a compatible version of the package. Release 0.2.1 should do:

```
git checkout 0.2.1
```

After this release, we introduced a few incompatible changes and still did not update the tutorial.  The decoder now does not accept the `embeddings_encoder` of type `SentenceEncoder`, but `embeddings_source` instead, which is an object of type `EmbeddedSequence`. 

If you want to use the master branch, you should do following changes to the configuration file:

First, split your encoder configuration section (let's say its called `[encoder]`) into these two:

```
[encoder]
class=encoders.recurrent.RecurrentEncoder
input_sequence=<input_embeddings>
rnn_size= ... <-- the original rnn_size
dropout_keep_prob= ... <-- the original dropout
attention_type=decoding_function.Attention
attention_state_size= ... <-- the original attention state size
rnn_cell= ... <-- the original rnn_cell (optional)

[input_embeddings]
class=model.sequence.EmbeddedSequence
vocabulary= ... <-- original vocabulary
data_id= ... <-- original data_id
embedding_size= ... <-- original embedding_size
max_length= ... <-- original max_length (if any)
```

Note that you should reuse all the configuration parameters you have in the original encoder configuration. Also note that assuming you are following the post-editing tutorial, the only encoder you need to alter this way is the one that processes the machine translated output.

Now, the last change is to replace the `embeddings_encoder` line from the decoder configuration with:
```
embeddings_source=<input_embeddings>
```

**Comment by supriyalk** [comment]
Using release 0.2.1, I get the error, ImportError: No module named 'magic'
I have tried using older released but still get the same error.

**Comment by jindrahelcl** [comment]
That's because since 0.2.1 we removed this dependency. You need a specific
version of the python-magic package. Look into the requirements.txt file
for details.

J

Dne 25. 7. 2017 11:38 odp. napsal uživatel "supriyalk" <
notifications@github.com>:
