### ISSUE TITLE
Wrong error when incorrect ini definition

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#510]
Following error is raised when I had a new line in config within string definition:
[main]
evaluation=[("target_beam", "target\n", <bleu>)]
...

2017-08-06 15:54:07: Failed to load INI file: Required argument `source' not given.
Traceback (most recent call last):
  File "neuralmonkey/config/configuration.py", line 70, in load_file
    self.raw_config, self.config_dict = parse_file(file, changes)
  File "neuralmonkey/config/parsing.py", line 176, in parse_file
    config = _parse_ini(config_file)
  File "neuralmonkey/config/parsing.py", line 137, in _parse_ini
    config.read_file(line_numbers, source=filename)
raise ValueError("Required argument `source' not given.")

**Comment by jlibovicky** [comment]
What would be an ideal error message then?

**Comment by tomkocmi** [comment]
Anything like "There is an error when parsing the ini file". Because currently, this error suggests that the ini was not even found.

**Comment by jindrahelcl** [comment]
I think the most appropriate error in this case is:
 
```
Series target
has not been found.
```

Anything else is a bug in parsing which should support newlines in strings (in general).
