### ISSUE TITLE
requirements-gpu.txt leads constantly to a problem 

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#545]
Hi,
I want to install the NM on a new venv, but come to the same issue every time:
`Collecting distribute (from pyter==0.2.2.1->-r requirements-gpu.txt (line 7))
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kbc4qwoo/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-build-kbc4qwoo/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-build-kbc4qwoo/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-build-kbc4qwoo/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-build-kbc4qwoo/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-build-kbc4qwoo/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kbc4qwoo/distribute/
`
Somebody already seen this?

Best,
Stoyan

**Comment by StoyanVenDimitrov** [comment]
Hi, 
I did `pip3.6 install --upgrade setuptools`  and then `pip install --upgrade -r requirements.txt`  but it leads to the same issue.

**Comment by jindrahelcl** [comment]
Ok try to `easy_install distribute`

**Comment by jindrahelcl** [comment]
See .travis.yml in the repo root dir

**Comment by marcwww** [comment]
> Ok try to `easy_install distribute`

'easy_install distribute'
then
'pip install pyter'
works.
