### ISSUE TITLE
Exception: Unexpected fields: runners_batch_size 

### ISSUE THREAD

**Issue by rupjyotiBaruah** [ufal/neuralmonkey#823]
During The Model Configuration when I fire the command
          **bin/neuralmonkey-train exp-nm-mt/translation.ini** 
It is processed in the following---
2019-06-23 12:13:06: Loading INI file: 'exp-nm-mt/translation.ini'
2019-06-23 12:13:06: INI file is parsed.
2019-06-23 12:13:06: Building model based on the config.
2019-06-23 12:13:06: Traceback (most recent call last):
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/train.py", line 66, in _main
    exp.train()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/experiment.py", line 243, in train
    self.build_model()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/experiment.py", line 207, in build_model
    self.config.build_model(warn_unused=self.train_mode)
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 89, in build_model
    self._check_loaded_conf()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 116, in _check_loaded_conf
    .format(", ".join(unexpected)))
**Exception: Unexpected fields: runners_batch_size**
Please correct me where I am wrong.
Thank you so much sir.

**Comment by jindrahelcl** [comment]
Hi,
the examples from the tutorials are outdated. If you leave the `runners_batch_size` parameter, it should work fine. You can refer to `tests/*.ini` for working examples of configuration files.
