### ISSUE TITLE
The Model Configuration in Machine Translation task

### ISSUE THREAD

**Issue by rupjyotiBaruah** [ufal/neuralmonkey#825]
During model configuration, after fired the command
**:~/neuralmonkey$ bin/neuralmonkey-train exp-nm-mt/translation.ini**
Exception an error! "Unexpected fields: runners_batch_size"

It raises the error in the following way:
2019-06-23 13:43:17: Loading INI file: 'exp-nm-mt/translation.ini'
2019-06-23 13:43:17: INI file is parsed.
2019-06-23 13:43:17: Building model based on the config.
2019-06-23 13:43:17: Traceback (most recent call last):
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/train.py", line 66, in _main
    exp.train()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/experiment.py", line 243, in train
    self.build_model()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/experiment.py", line 207, in build_model
    self.config.build_model(warn_unused=self.train_mode)
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 89, in build_model
    self._check_loaded_conf()
  File "/home/rupjyoti/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 116, in _check_loaded_conf
    .format(", ".join(unexpected)))
**Exception: Unexpected fields: runners_batch_size**

Any help for correcting is much appreciated.

Thank you so much

**Comment by jindrahelcl** [comment]
de-duping with #823
