### ISSUE TITLE
tensorflow and termcolor problem: ImportError: cannot import name DEBUG

### ISSUE THREAD

**Issue by jvdbogae** [ufal/neuralmonkey#89]
I get the following error when doing

> import tensorflow as tf

I suspect it has to do with termcolor, since I do not get the error when I uninstall termcolor.
I am running tensorflow in a conda environment.

Tensorflow version is.
Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

cuda version is.
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

CuDNN version is. 4

This is the output I get.
(tensorflow)joachim@countcount ~/repositories/neuralmonkey/neuralmonkey $ python train.py 
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import tensorflow as tf
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 65, in <module>
    import tensorflow.contrib as contrib
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import stochastic_graph
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/bayesflow/python/ops/stochastic_graph.py", line 51, in <module>
    from tensorflow.python.framework import ops
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.framework import registry
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/registry.py", line 28, in <module>
    from tensorflow.python.platform import tf_logging as logging
  File "/home/joachim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/tf_logging.py", line 28, in <module>
    from logging import DEBUG
ImportError: cannot import name DEBUG

**Comment by jvdbogae** [comment]
Sorry, seems to be a local problem with tensorflow.

**Comment by jindrahelcl** [comment]
> Tensorflow version is.
Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

It seems you are using TF for older Python. It should be TF for Python 3.5

**Comment by jvdbogae** [comment]
Tensorflow is now running correctly, but I get the following error. Any ideas?
AttributeError: module 'logging' has no attribute 'Handler'

Here is the trace:

(tensorflow_python_3_5) joachim@countcount ~/repositories/neuralmonkey $ python neuralmonkey/train.py examples/translation.ini 
Traceback (most recent call last):
  File "neuralmonkey/train.py", line 10, in <module>
    import tensorflow as tf
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    import numpy as np
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/unittest/__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/unittest/case.py", line 273, in <module>
    class _CapturingHandler(logging.Handler):
AttributeError: module 'logging' has no attribute 'Handler'

**Comment by jindrahelcl** [comment]
You need to run this:
bin/neuralmonkey-train examples/translation.ini
