### ISSUE TITLE
No documentation for running neuralmonkey

### ISSUE THREAD

**Issue by jvdbogae** [ufal/neuralmonkey#91]
If I run

`./bin/neuralmonkey-run ./examples/translation.ini ./examples/data/val.en`

I get the following error. Also, python becomes defunct, and I need to reboot -f to get back into my machine. What am I doing wrong? It looks like an .ini file is expected as input file

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
2016-09-19 17:14:21: Loading INI file: './examples/translation.ini'
2016-09-19 17:14:21: INI file is parsed.
DEBUG (configBuild):Building value on depth 0: ['object:bleu1', 'object:bleu4']
DEBUG (configBuild):Building value on depth 1: object:bleu1
DEBUG (configBuild):Building value on depth 2: 1
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.evaluators.bleu.BLEUEvaluator'> with arguments {'n': 1}
DEBUG (configBuild):Class <class 'neuralmonkey.evaluators.bleu.BLEUEvaluator'> initialized into object <neuralmonkey.evaluators.bleu.BLEUEvaluator object at 0x7f2086e1d3c8>
DEBUG (configBuild):Building value on depth 1: object:bleu4
DEBUG (configBuild):Building value on depth 2: 4
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.evaluators.bleu.BLEUEvaluator'> with arguments {'n': 4}
DEBUG (configBuild):Class <class 'neuralmonkey.evaluators.bleu.BLEUEvaluator'> initialized into object <neuralmonkey.evaluators.bleu.BLEUEvaluator object at 0x7f20c70f6be0>
DEBUG (configBuild):Building value on depth 0: out-example-translation
DEBUG (configBuild):Building value on depth 0: object:bpe_postprocess
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.processors.bpe.BPEPostprocessor'> with arguments {}
DEBUG (configBuild):Class <class 'neuralmonkey.processors.bpe.BPEPostprocessor'> initialized into object <neuralmonkey.processors.bpe.BPEPostprocessor object at 0x7f20c70eabe0>
DEBUG (configBuild):Building value on depth 0: 4
DEBUG (configBuild):Building value on depth 0: object:runner
DEBUG (configBuild):Building value on depth 1: object:decoder
DEBUG (configBuild):Building value on depth 2: 256
DEBUG (configBuild):Building value on depth 2: 0.8
DEBUG (configBuild):Building value on depth 2: 50
DEBUG (configBuild):Building value on depth 2: target
DEBUG (configBuild):Building value on depth 2: True
DEBUG (configBuild):Building value on depth 2: 300
DEBUG (configBuild):Building value on depth 2: object:target_vocabulary
DEBUG (configBuild):Building value on depth 3: 50000
DEBUG (configBuild):Building value on depth 3: ['object:train_data']
DEBUG (configBuild):Building value on depth 4: object:train_data
DEBUG (configBuild):Building value on depth 5: examples/data/train.en
DEBUG (configBuild):Building value on depth 5: object:bpe_preprocess
DEBUG (configBuild):Building value on depth 6: examples/data/bpe_merges
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.processors.bpe.BPEPreprocessor'> with arguments {'merge_file': 'examples/data/bpe_merges'}
2016-09-19 17:14:21: Initializing BPE preprocessor
DEBUG (configBuild):Class <class 'neuralmonkey.processors.bpe.BPEPreprocessor'> initialized into object <neuralmonkey.processors.bpe.BPEPreprocessor object at 0x7f20b745c7b8>
DEBUG (configBuild):Building value on depth 5: examples/data/train.de
DEBUG (configBuild):Instantiating class <function load_dataset_from_files at 0x7f20b7426488> with arguments {'s_source': 'examples/data/train.en', 'preprocessor': <neuralmonkey.processors.bpe.BPEPreprocessor object at 0x7f20b745c7b8>, 's_target': 'examples/data/train.de'}
2016-09-19 17:14:21: Initializing dataset with: source, target
2016-09-19 17:14:21: Loading examples/data/train.en
2016-09-19 17:14:38: Loading examples/data/train.de
2016-09-19 17:15:13: Dataset length: 500000
DEBUG (configBuild):Class <function load_dataset_from_files at 0x7f20b7426488> initialized into object <neuralmonkey.dataset.Dataset object at 0x7f20792da898>
DEBUG (configBuild):Building value on depth 3: ['target']
DEBUG (configBuild):Building value on depth 4: target
DEBUG (configBuild):Building value on depth 3: tmp-decoder-vocabulary
DEBUG (configBuild):Building value on depth 3: decoder_vocabulary
DEBUG (configBuild):Instantiating class <function initialize_vocabulary at 0x7f20b7433d90> with arguments {'max_size': 50000, 'directory': 'tmp-decoder-vocabulary', 'name': 'decoder_vocabulary', 'datasets': [<neuralmonkey.dataset.Dataset object at 0x7f20792da898>], 'series_ids': ['target']}
2016-09-19 17:15:13: Warning! Use of deprecated initialize_vocabulary method. Did you think this through?
2016-09-19 17:15:13: Pickled vocabulary loaded. Size: 39041 words
2016-09-19 17:15:13: Sample of the vocabulary: ['loose', 'aufs@@', 'bewusstsein', 'corporate', 'Verstän@@']
DEBUG (configBuild):Class <function initialize_vocabulary at 0x7f20b7433d90> initialized into object <neuralmonkey.vocabulary.Vocabulary object at 0x7f20b745c748>
DEBUG (configBuild):Building value on depth 2: ['object:encoder']
DEBUG (configBuild):Building value on depth 3: object:encoder
DEBUG (configBuild):Building value on depth 4: 300
DEBUG (configBuild):Building value on depth 4: 50
DEBUG (configBuild):Building value on depth 4: 0.8
DEBUG (configBuild):Building value on depth 4: source
DEBUG (configBuild):Building value on depth 4: 300
DEBUG (configBuild):Building value on depth 4: <class 'neuralmonkey.decoding_function.Attention'>
DEBUG (configBuild):Building value on depth 4: object:source_vocabulary
DEBUG (configBuild):Building value on depth 5: 50000
DEBUG (configBuild):Building value on depth 5: ['object:train_data']
DEBUG (configBuild):Building value on depth 6: object:train_data
DEBUG (configBuild):Skipping already initialized value: object:train_data
DEBUG (configBuild):Building value on depth 5: ['source']
DEBUG (configBuild):Building value on depth 6: source
DEBUG (configBuild):Building value on depth 5: tmp-encoder-vocabulary
DEBUG (configBuild):Building value on depth 5: encoder_vocabulary
DEBUG (configBuild):Instantiating class <function initialize_vocabulary at 0x7f20b7433d90> with arguments {'max_size': 50000, 'directory': 'tmp-encoder-vocabulary', 'name': 'encoder_vocabulary', 'datasets': [<neuralmonkey.dataset.Dataset object at 0x7f20792da898>], 'series_ids': ['source']}
2016-09-19 17:15:13: Warning! Use of deprecated initialize_vocabulary method. Did you think this through?
2016-09-19 17:15:13: Pickled vocabulary loaded. Size: 23792 words
2016-09-19 17:15:13: Sample of the vocabulary: ['feu@@', 'C-@@', 'fu@@', 'gs', 'bes@@']
DEBUG (configBuild):Class <function initialize_vocabulary at 0x7f20b7433d90> initialized into object <neuralmonkey.vocabulary.Vocabulary object at 0x7f2078feedd8>
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.encoders.sentence_encoder.SentenceEncoder'> with arguments {'rnn_size': 300, 'max_input_len': 50, 'dropout_keep_p': 0.8, 'data_id': 'source', 'embedding_size': 300, 'attention_type': <class 'neuralmonkey.decoding_function.Attention'>, 'vocabulary': <neuralmonkey.vocabulary.Vocabulary object at 0x7f2078feedd8>}
2016-09-19 17:15:13: Initializing sentence encoder, name: "sentence_encoder"
2016-09-19 17:15:18: Sentence encoder initialized
DEBUG (configBuild):Class <class 'neuralmonkey.encoders.sentence_encoder.SentenceEncoder'> initialized into object <neuralmonkey.encoders.sentence_encoder.SentenceEncoder object at 0x7f2078feeda0>
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.decoders.decoder.Decoder'> with arguments {'rnn_size': 256, 'dropout_keep_p': 0.8, 'max_output_len': 50, 'data_id': 'target', 'use_attention': True, 'embedding_size': 300, 'vocabulary': <neuralmonkey.vocabulary.Vocabulary object at 0x7f20b745c748>, 'encoders': [<neuralmonkey.encoders.sentence_encoder.SentenceEncoder object at 0x7f2078feeda0>]}
2016-09-19 17:15:18: Initializing decoder, name: 'decoder'
2016-09-19 17:15:20: Decoder initialized.
DEBUG (configBuild):Class <class 'neuralmonkey.decoders.decoder.Decoder'> initialized into object <neuralmonkey.decoders.decoder.Decoder object at 0x7f20b745c7f0>
DEBUG (configBuild):Building value on depth 1: 256
DEBUG (configBuild):Instantiating class <class 'neuralmonkey.runners.runner.GreedyRunner'> with arguments {'decoder': <neuralmonkey.decoders.decoder.Decoder object at 0x7f20b745c7f0>, 'batch_size': 256}
DEBUG (configBuild):Class <class 'neuralmonkey.runners.runner.GreedyRunner'> initialized into object <neuralmonkey.runners.runner.GreedyRunner object at 0x7f20c517f630>
DEBUG (configBuild):Building value on depth 0: object:decoder
DEBUG (configBuild):Skipping already initialized value: object:decoder
DEBUG (configBuild):Building value on depth 0: ['object:encoder']
DEBUG (configBuild):Building value on depth 1: object:encoder
DEBUG (configBuild):Skipping already initialized value: object:encoder
2016-09-19 17:15:20: INI file loaded.

2016-09-19 17:15:20: Initializing the TensorFlow session.
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:0b:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x168659f0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:06:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:0b:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
2016-09-19 17:15:26: Loading variables from out-example-translation/variables.data.best
2016-09-19 17:15:27: Session initialization done.

2016-09-19 17:15:27: Loading INI file: './examples/data/val.en'
2016-09-19 17:15:27: Failed to load INI file: File contains no section headers.
file: '', line: 1
'in the resolution , we recommend frontloading subject to cautious conditions . 1'
Traceback (most recent call last):
  File "/home/joachim/repositories/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 44, in load_file
    config_dict = load_config_file(config_f, self.ignored)
  File "/home/joachim/repositories/neuralmonkey/bin/neuralmonkey/config/config_loader.py", line 122, in load_config_file
    config_dicts = parsing.parse_file(config_file)
  File "/home/joachim/repositories/neuralmonkey/bin/neuralmonkey/config/parsing.py", line 173, in parse_file
    config = parse_config(config_file)
  File "/home/joachim/repositories/neuralmonkey/bin/neuralmonkey/config/parsing.py", line 157, in parse_config
    config.read_file(line_numbers, source=filename)
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/home/joachim/anaconda2/envs/tensorflow_python_3_5/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '', line: 1
'in the resolution , we recommend frontloading subject to cautious conditions . 1'
```

**Comment by jindrahelcl** [comment]
the correct way to run neuralmonkey is to supply two .ini files. The first file is the file with the model description and the second one is the file with dataset description. I will add the proper documentation tomorrow. Meanwhile, you can look inside the `run.py` script to figure out what is needed in the second ini file.

**Comment by jindrahelcl** [comment]
This is how the second ini should look like:

```
[main]
test_datasets=[<news>]

[bpe_preprocess]
class=processors.bpe.BPEPreprocessor
merge_file=/home/user/experiments/merges.bpe

[news]
class=config.utils.dataset_from_files
s_source=/home/user/data/newstest/news.de
s_target_out=/home/user/experiments/news/news.out.en
preprocess=<bpe_preprocess>
```


Note that you can specify more datasets at once. Also note that for each dataset, you must provide the source data series and the target_out data series. These names should match the encoder and decoder data series names provided in the model configuration file.

**Comment by jvdbogae** [comment]
Thanks, it seems to work now.  The crashes I experienced seem to stem from ubuntu 14, as described in [https://github.com/tensorflow/tensorflow/issues/1203](url).

**Comment by jindrahelcl** [comment]
I am preparing a tutorial here: http://neural-monkey.readthedocs.io/en/latest/tutorial.html if you want to check it out..

**Comment by jindrahelcl** [comment]
The tutorial now contains the description of how to prepare the test dataset file and how to run it.
